// Make an object with all problem body parts
// Parts can either have a count of 1 (like your spine), 2 (like your legs), 10 (like a set of toes),
// or 20 for groups of things too big to be counted (like pores) and should always be talked about as a group

var bodyparts = [
 {singular: "ankle", plural: "ankles", count: 2},
 {singular: "arm", plural: "arms", count: 2},
 {singular: "back", plural: "ankles", count: 1},
 {singular: "belly button", count: 1},
 {singular: "bicep", plural: "biceps", count: 2},
 {singular: "boob", plural: "boobs", count: 2},
 {singular: "bottom", count: 1},
 {singular: "breast", plural: "breasts", count: 2},
 {singular: "butt", count: 1},
 {singular: "calf", plural: "calves", count: 2},
 {singular: "cheek", plural: "cheeks", count: 2},
 {singular: "chest", count: 1},
 {singular: '"down there"', count: 1},
 {singular: "earlobe", plural: "earlobes", count: 2},
 {singular: "ear", plural: "ears", count: 2},
 {singular: "elbow", plural: "elbows", count: 2},
 {singular: "eyebrow", plural: "eyebrows", count: 2},
 {singular: "eyelash", plural: "eyelashes", count: 10},
 {singular: "eyelid", plural: "eyelids", count: 2},
 {singular: "eye", plural: "eyes", count: 2},
 {singular: "face", count: 1},
 {singular: "foot", plural: "feet",  count: 2},
 {singular: "forearm", plural: "forearms", count: 2},
 {singular: "freckle", plural: "freckles", count: 20},
 {singular: "hairline", count: 1},
 {singular: "hair", count: 1},
 {singular: "heel", plural: "heels", count: 2},
 {singular: "hipbone", plural: "hipbones", count: 2},
 {singular: "hip", plural: "hips", count: 2},
 {singular: "knee", plural: "knees", count: 2},
 {singular: "leg", plural: "legs", count: 2},
 {singular: "lip", plural: "lips", count: 2, set: "vertical"},
 {singular: "lower back", count: 1},
 {singular: "nail bed", plural: "nail beds", count: 10},
 {singular: "nail", plural: "nails", count: 10},
 {singular: "neck", count: 1},
 {singular: "nipple", plural: "nipples", count: 2},
 {singular: "pore", plural: "pores", count: 20},
 {singular: "rib", plural: "ribs", count: 2},
 {singular: "shin", plural: "shins", count: 2},
 {singular: "shoulder", plural: "shoulders", count: 2},
 {singular: "spine", count: 1},
 {singular: "split end", plural: "split ends", count: 20},
 {singular: "stomach", count: 1},
 {singular: "tear duct", plural: "tear ducts", count: 2},
 {singular: "thigh", plural: "thighs", count: 2},
 {singular: "tooth", plural: "teeth", count: 20},
 {singular: "toenail", plural: "toenails", count: 10},
 {singular: "toe", plural: "toes", count: 10},
 {singular: "tummy", count: 1},
 {singular: "vagina", count: 1}
];